language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"

notifications:
  email: false